import type { PropsWithChildren, ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View, type StyleProp, type TextStyle, type ViewStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { color, layout, radius, space, type } from './tokens';
type TextVariant = keyof typeof type;
export function AppText({ variant='body', tone='primary', style, children }: PropsWithChildren<{variant?:TextVariant;tone?:'primary'|'secondary'|'tertiary'|'inverse';style?:StyleProp<TextStyle>}>) { return <Text style={[styles.text,type[variant],{color:color.text[tone]},style]}>{children}</Text>; }
export function Screen({children,scroll=true,style}:PropsWithChildren<{scroll?:boolean;style?:StyleProp<ViewStyle>}>) { const content=<View style={[styles.screenContent,style]}>{children}</View>; return <SafeAreaView edges={['top']} style={styles.safe}>{scroll?<ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>{content}</ScrollView>:content}</SafeAreaView>; }
export function Card({children,style}:PropsWithChildren<{style?:StyleProp<ViewStyle>}>) { return <View style={[styles.card,style]}>{children}</View>; }
export function Button({label,onPress,variant='primary',disabled=false,style}:{label:string;onPress?:()=>void;variant?:'primary'|'subtle'|'ghost';disabled?:boolean;style?:StyleProp<ViewStyle>}) { return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={({pressed})=>[styles.button,styles[variant],pressed&&!disabled&&styles.pressed,disabled&&styles.disabled,style]}><AppText variant="label" tone={variant==='primary'?'inverse':'primary'}>{label}</AppText></Pressable>; }
export function IconButton({label,icon,onPress}:{label:string;icon:string;onPress?:()=>void}) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({pressed})=>[styles.iconButton,pressed&&styles.pressed]}><AppText variant="heading">{icon}</AppText></Pressable>; }
export function ScreenHeader({title,back,right}:{title?:string;back?:()=>void;right?:ReactNode}) { return <View style={styles.header}>{back?<IconButton label="뒤로 가기" icon="‹" onPress={back}/>:<View style={styles.headerSide}/>}<AppText variant="heading" style={styles.headerTitle}>{title}</AppText>{right??<View style={styles.headerSide}/>}</View>; }
export function AppInput({value,onChangeText,placeholder,label,maxLength}:{value:string;onChangeText:(text:string)=>void;placeholder:string;label:string;maxLength?:number}) { return <TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor={color.text.tertiary} maxLength={maxLength} style={styles.input}/>; }
export function SelectionCard({label,detail,selected,onPress,style}:{label:string;detail?:string;selected?:boolean;onPress?:()=>void;style?:StyleProp<ViewStyle>}) { return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{selected}} onPress={onPress} style={({pressed})=>[styles.selection,selected&&styles.selectionSelected,pressed&&styles.pressed,style]}><AppText variant="label">{label}</AppText>{detail?<AppText variant="caption" tone="secondary">{detail}</AppText>:null}</Pressable>; }
export function BottomTabs({active,onToday,onRecords,onStudio}:{active:'today'|'records'|'studio';onToday:()=>void;onRecords:()=>void;onStudio:()=>void}) { const tabs=[{id:'today' as const,icon:'⌂',label:'홈',fn:onToday},{id:'records' as const,icon:'▣',label:'기록',fn:onRecords},{id:'studio' as const,icon:'◌',label:'스튜디오',fn:onStudio}]; return <View style={styles.tabs}>{tabs.map(tab=><Pressable key={tab.id} accessibilityRole="tab" accessibilityState={{selected:active===tab.id}} onPress={tab.fn} style={styles.tab}><AppText variant="heading" tone={active===tab.id?'primary':'tertiary'}>{tab.icon}</AppText><AppText variant="caption" tone={active===tab.id?'primary':'tertiary'}>{tab.label}</AppText></Pressable>)}</View>; }
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:color.bg.canvas},scroll:{flexGrow:1},screenContent:{width:'100%',maxWidth:layout.contentMaxWidth,alignSelf:'center',paddingHorizontal:layout.screenHorizontal,paddingTop:layout.screenTop,paddingBottom:space[8],gap:space[4]},text:{includeFontPadding:false},card:{backgroundColor:color.bg.surface,borderRadius:radius.card,padding:space[5],gap:space[2],borderWidth:1,borderColor:color.border.default,shadowColor:'#495463',shadowOpacity:.05,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:1},button:{minHeight:layout.hitTarget,alignItems:'center',justifyContent:'center',borderRadius:radius.control,paddingHorizontal:space[5]},primary:{backgroundColor:color.action.primary},subtle:{backgroundColor:color.action.subtle},ghost:{backgroundColor:'transparent'},pressed:{opacity:.72},disabled:{opacity:.45},iconButton:{width:layout.hitTarget,height:layout.hitTarget,alignItems:'center',justifyContent:'center',borderRadius:radius.full},header:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{flex:1,textAlign:'center'},headerSide:{width:layout.hitTarget},input:{minHeight:layout.hitTarget,borderWidth:1,borderColor:color.border.default,borderRadius:radius.control,paddingHorizontal:space[4],color:color.text.primary,...type.body,backgroundColor:color.bg.surface},selection:{minHeight:76,justifyContent:'center',backgroundColor:color.bg.surface,borderRadius:radius.control,borderWidth:1,borderColor:color.border.default,padding:space[3],gap:space[1]},selectionSelected:{backgroundColor:color.bg.selected,borderColor:color.action.primary},tabs:{minHeight:layout.tabBarHeight,borderTopWidth:1,borderColor:color.border.default,backgroundColor:color.bg.surface,flexDirection:'row',justifyContent:'space-around',paddingBottom:space[2]},tab:{flex:1,minHeight:layout.hitTarget,alignItems:'center',justifyContent:'center',gap:1}});
